---
- name: restart ser2net
  service: name=ser2net state=restarted
- name: recompile uboot scripts
  command: /usr/bin/make chdir=/boot/
- name: restart sysfsutils
  service: name=sysfsutils state=restarted
...
