---
sunxi_uboot_blkdev: mmcblk2
sunxi_root_dev: mmcblk2
sunxi_mmc: 1
sunxi_dtb: sun8i-h3-orangepi-plus
sunxi_overlays:
- h3-i2cs
- h3-bme280
- h3-si7020
- h3-h5-analog-codec
sunxi_uboot_defconfig: orangepi_plus_defconfig
...
