---
ipv4_address: 172.21.42.5
ipv6_address: 2001:1540:802:4:8873:a5ff:fead:de64
sunxi_uboot_blkdev: mmcblk2
sunxi_root_dev: mmcblk2
sunxi_mmc: 1
sunxi_dtb: sun8i-h3-orangepi-plus
sunxi_overlays:
- i2cs
- bme280
- si7020
- analog-codec
sunxi_uboot_defconfig: orangepi_plus_defconfig
...
