---
ipv4_address: 172.21.42.23
ipv6_address: 2001:1540:802:4:821f:2ff:fe89:afb6
sunxi_uboot_blkdev: mmcblk2
sunxi_root_dev: mmcblk2
sunxi_mmc: 1
sunxi_dtb: allwinner/sun50i-h5-orangepi-zero-plus2
sunxi_overlays:
- usbhost2
- usbhost3
sunxi_uboot_defconfig: orangepi_zero_plus2_defconfig
...
