---
sunxi_uboot_blkdev: mmcblk2
sunxi_root_dev: mmcblk2
sunxi_mmc: 1
sunxi_dtb: allwinner/sun50i-h5-orangepi-zero-plus2
sunxi_overlays:
- h3-h5-analog-codec
- h5-cir
- h5-usbhost2
- h5-usbhost3
sunxi_uboot_defconfig: orangepi_zero_plus2_defconfig
...
