---
- name: Remove Carbon/sunxi from fstab
  mount:
    name: "{{ sunxi_mountpoint }}"
    src: "{{ sunxi_src }}"
    fstype: nfs
    state: absent
- name: Remove deprecated mountpoint
  file:
    path: "{{ sunxi_mountpoint }}"
    state: absent
- name: Remove unneeded packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
  - ser2net
  - sysfsutils
- name: Remove unneeded bootfiles
  file:
    name: "/boot/{{ item }}"
    state: absent
  with_items:
  - "patch.cmd"
  - "patch.scr"
  - "scripts.results.scr"
  - "uboot_scripts.results.scr"
  - "u-boot-sunxi-with-spl.bin.2016.07"
  - "zImage2"
  - "opi.dtb2"
- name: Remove devboard stuff from hosts outside devsetup
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/etc/ser2net.conf"
  - "/usr/local/sbin/sunxi-reboot-other.sh"
  - "/etc/sysfs.d/sunxi-reboot-other.conf"
  when: "'sunxi_thuis_dev' not in group_names"
...
